# Generated by Django 4.0.3 on 2022-04-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='producto',
            new_name='propiedad',
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='producto',
            new_name='propiedad',
        ),
    ]
