# Generated by Django 4.0.3 on 2022-04-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_rename_producto_detalle_propiedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='estates.propiedad'),
        ),
    ]
