# Generated by Django 4.0.3 on 2022-04-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_alter_informacionextra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionextra',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='informacionextra',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
